name: Curl-er

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      githubUser:
        required: true
        type: string
      githubRepo:
        required: true
        type: string
      artifact:
        required: true
        type: string
    
jobs:
  get-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
            sudo apt-get install -y curl
    
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Config Git
        run: |
          git config --global user.name "8an4nam1ni0n"
          git config --global user.email "24194029+8ana4nam1ni0n@users.noreply.github.com"
          mkdir -p ${{ inputs.directory }}

      - name: Get Artifact
        run: |
          cd ${{ inputs.directory }}
          FILENAME=$(ls)
          LATEST_VERSION=$(curl -s https://api.github.com/repos/${{ inputs.githubUser }}/${{ inputs.githubRepo }}/releases/latest | jq -r '.tag_name')
          VERSION_STRING=$(echo $LATEST_VERSION | grep -oE "v?([0-9]+\.){2}[0-9]+")
          ARTIFACT=$(echo ${{ inputs.artifact }} | sed -e 's/VERSION/'$VERSION_STRING'/')
          curl -L https://github.com/${{ inputs.githubUser }}/${{ inputs.githubRepo }}/releases/download/$LATEST_VERSION/$ARTIFACT -o $ARTIFACT
          if ! test -z $FILENAME; then
            [ $FILENAME != $ARTIFACT ] && UPDATE=1 || UPDATE=0
          else
            UPDATE=0
          fi
          echo "NEEDS_UPDATE=$UPDATE" >> $GITHUB_ENV
          echo "ARTIFACT=$ARTIFACT" >> $GITHUB_ENV
          cd -
        
      - name: Commit and Push
        run: |
          if (( $NEEDS_UPDATE == 1)); then
              [ -f ${{ inputs.directory }}/$ARTIFACT ] && rm  ${{ inputs.directory }}/$ARTIFACT
              git add .
              git commit -m "Updated $ARTIFACT to $LATEST_VERSION"
              git push origin main
          fi
