name: Fd-Find

on: workflow_dispatch
  
jobs:
  call-curler:
    uses: ./.github/workflows/curler-reusable.yml
    with:
      directory: fd
      githubUser: sharkdp
      githubRepo: fd
      artifact: fd-VERSION-x86_64-unknown-linux-musl.tar.gz
      artifactOutput: fd
