name: Fd-Find

on: 
  schedule:
  - cron: "0 6 * * 1"
  
jobs:
  get-fd-find:
    runs-on: ubuntu-latest

    steps:

      - name: Install Dependencies
        run: |
            sudo apt-get install -y curl
    
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Config Git
        run: |
          git config --global user.name "8an4nam1ni0n"
          git config --global user.email "24194029+8ana4nam1ni0n@users.noreply.github.com"
          mkdir -p fd
        
      - name: Get fd-find
        run: |
          cd fd
          FILENAME=$(ls)
          CURRENT_VERSION=$(echo $FILENAME | sed -n 's/.*-\(v[0-9.]*\)\.tar\.gz/\1/p')
          LATEST_VERSION=$(curl -s https://api.github.com/repos/sharkdp/fd/releases/latest | jq -r '.tag_name')
          curl -L https://github.com/sharkdp/fd/releases/download/$LATEST_VERSION/fd-$LATEST_VERSION-x86_64-unknown-linux-musl.tar.gz -o fd-$LATEST_VERSION.tar.gz
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          cd -
        
      - name: Commit and Push
        run: |
          if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
              [ -f fd/fd-$CURRENT_VERSION.tar.gz ] && rm fd/fd-$CURRENT_VERSION.tar.gz
              git add .
              git commit -m "Updated Fd-Find to $LATEST_VERSION"
              git push origin main
          fi
