name: HelmLs

on:
  workflow_dispatch:
  schedule:
  - cron: "0 6 * * 1"

jobs:
  call-curler:
    uses: ./.github/workflows/curler-reusable.yml
    with:
      directory: lsp/helm
      githubUser: mrjosh
      githubRepo: helm-ls
      artifact: helm_ls_linux_amd64
