name: "Lombok Jar"

on:
  schedule:
  - cron: "0 6 * * 1"
  
  workflow_dispatch:

jobs:
  get-lombok:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.get-lombok.outputs.artifact }}
      package-name: ${{ steps.get-lombok.outputs.package-name }}

    steps:
      - name: Add dependencies
        run: |
          sudo apt-get install -y curl
          
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Get Lombok
        id: get-lombok
        run: |
          artifact="lombok"
          packageName="$artifact.jar"
          curl -LO https://projectlombok.org/downloads/lombok.jar
          echo "artifact=$artifact" >> $GITHUB_OUTPUT
          echo "package-name=$packageName" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.get-lombok.outputs.artifact }}
          path: ${{ steps.get-lombok.outputs.package-name }}
          retention-days: 1
  
  commit-and-push:
    runs-on: ubuntu-latest
    needs: get-lombok
    steps:
      - uses: actions/checkout@v4

      - name: Update Repo From Remote
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.get-lombok.outputs.artifact }}

      - name: Move artifact
        run: |
          ls -R
          mkdir -p java-tools/libs
          mv -f ${{ needs.get-lombok.outputs.package-name }} java-tools/libs/

      # Runs a set of commands using the runners shell
      - name: Check For Updates
        id: git-check
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "needs-update=false" >> $GITHUB_OUTPUT
          else
            echo "needs-update=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push
        if: steps.git-check.outputs.needs-update == 'true'
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add ${{ inputs.directory }}/
          git commit -m "Updated ${{ needs.get-artifact.outputs.artifact }}"
          git push origin main
