name: MdCat

on:
  schedule:
  - cron: "0 6 * * 1"

jobs:
  call-curler:
    uses: ./.github/workflows/curler-reusable.yml
    with:
      directory: mdcat
      githubUser: swsnr
      githubRepo: mdcat
      artifact: mdcat-VERSION-x86_64-unknown-linux-musl.tar.gz
