name: Neovim

on:
  workflow_dispatch:
  schedule:
  - cron: "0 6 * * 1"
  
jobs:
  get-neovim:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt-get install -y curl

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Config Git
        run: |
          git config --global user.name "8an4nam1ni0n"
          git config --global user.email "24194029+8ana4nam1ni0n@users.noreply.github.com"
          mkdir -p nvim

      - name: Fetch Neovim Nightly
        run: |
          cd nvim
          curl -L https://github.com/neovim/neovim-releases/releases/download/nightly/nvim-linux-x86_64.tar.gz -o nvim-nightly.tar.gz
          cd -

      - name: Commit and Push
        run: |
         git remote update
          if ! git status -uno | grep -q 'Your branch is up to date'; then
            echo "Changes detected on the remote repository. Performing git pull..."
            git pull
          fi
          if [ -n "$(git status --porcelain)" ]; then
            echo "There are changes to commit"
            git add .
            git commit -m "Updated neovim nightly to most recent build"
            git push origin main
          else
            echo "No changes to commit"
          fi          
