name: Neovim

on: workflow_dispatch
  
jobs:
  get-neovim:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt-get install -y curl

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch Neovim Nightly
        run: |
          mkdir -p nvim
          cd nvim
          curl -L https://github.com/neovim/neovim-releases/releases/download/nightly/nvim-linux64.tar.gz -o nvim-nightly.tar.gz
          cd -

      - name: Commit and Push
        run: |
         git add .
         git commit -m "Updated neovim nightly to most recent build"
         git push origin main
          
