name: Neovim

on: workflow_dispatch
  
jobs:
  call-curler:
    uses: ./.github/workflows/curler-reusable.yml
    with:
      directory: nvim
      githubUser: neovim
      githubRepo: neovim
      artifact: nvim-linux64.tar.gz
      artifactOutput: nvim
