name: Neovim

on:
  schedule:
  - cron: "0 6 * * 1"
    
jobs:
  get-neovim:
    runs-on: ubuntu-latest

    steps:

      - name: Install Dependencies
        run: |
            sudo apt-get install -y build-essential cmake curl gettext ninja-build unzip
    
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Config Git
        run: |
          git config --global user.name "8an4nam1ni0n"
          git config --global user.email "24194029+8ana4nam1ni0n@users.noreply.github.com"
    
      - name: Clone And Build
        run: |
          git clone https://github.com/neovim/neovim.git
          cd neovim
          make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=/opt
          make install

      - name: Build Neovim Portable
        run: |
          cd neovim
          make CMAKE_BUILD_TYPE=RelWithDebInfo
          make CMAKE_INSTALL_PREFIX=../../nvim install
          cd -
          rm -rf neovim
        
      - name: Commit and Push
        run: |
          git add .
          git commit -m "Updated and Build Neovim"
          git push origin main
