name: Ripgrep

on: workflow_dispatch
  
  
jobs:
  get-ripgrep:
    runs-on: ubuntu-latest

    steps:

      - name: Install Dependencies
        run: |
            sudo apt-get install -y curl
    
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Config Git
        run: |
          git config --global user.name "8an4nam1ni0n"
          git config --global user.email "24194029+8ana4nam1ni0n@users.noreply.github.com"
          mkdir -p ripgrep
        
      - name: Get ripgrep
        run: |
          cd fd
          FILENAME=$(ls)
          CURRENT_VERSION=$(echo $FILENAME | sed -n 's/.*-\([0-9.]*\)\.tar\.gz/\1/p')
          LATEST_VERSION=$(curl -s https://api.github.com/repos/BurntSushi/ripgrep/releases/latest | jq -r '.tag_name')
          curl -L https://github.com/BurntSushi/ripgrep/releases/download/$LATEST_VERSION/ripgrep-$LATEST_VERSION-x86_64-unknown-linux-musl.tar.gz -o ripgrep-$LATEST_VERSION.tar.gz
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          cd -
        
      - name: Commit and Push
        run: |
          if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
              [ -f fd/fd-$CURRENT_VERSION.tar.gz ] && rm fd/fd-$CURRENT_VERSION.tar.gz
              git add .
              git commit -m "Updated ripgrep to $LATEST_VERSION"
              git push origin main
          fi
