name: Ripgrep

on:
  schedule:
  - cron: "0 6 * * 1"

jobs:
  call-curler:
    uses: ./.github/workflows/curler-reusable.yml
    with:
      directory: ripgrep
      githubUser: BurntSushi
      githubRepo: ripgrep
      artifact: ripgrep-VERSION-x86_64-unknown-linux-musl.tar.gz
      artifactOutput: ripgrep
