name: Starship

on: workflow_dispatch
  
jobs:
  call-curler:
    uses: ./.github/workflows/curler-reusable.yml
    with:
      directory: starship
      githubUser: starship
      githubRepo: starship
      artifact: starship-VERSION-x86_64-unknown-linux-musl.tar.gz
      artifactOutput: starship
