name: Starship

on:
  schedule:
  - cron: "0 6 * * 1"

jobs:
  call-curler:
    uses: ./.github/workflows/curler-reusable.yml
    with:
      directory: starship
      githubUser: starship
      githubRepo: starship
      artifact: starship-x86_64-unknown-linux-musl.tar.gz
