name: Clean All Workflow Runs

on:
  workflow_dispatch:
  schedule:
  - cron: "0 4 * * 1"

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Delete completed runs for all workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 5
