name: Zellij

on:
  workflow_dispatch:
  
  schedule:
  - cron: "0 6 * * 1"
  


jobs:
  call-curler:
    uses: ./.github/workflows/curler-reusable.yml
    with:
      directory: zellij
      githubUser: zellij-org
      githubRepo: zellij
      artifact: zellij-x86_64-unknown-linux-musl.tar.gz
